import '@/styles/common.scss';
import '@/assets/font.css';
import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import router from './router';
import { lazyPlugin } from '@/directives/lazy-p.js';
import { componentPlugin } from '@/components/index.js';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import 'element-plus/theme-chalk/el-message.css';
import 'element-plus/theme-chalk/el-message-box.css';
const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
const app = createApp(App);
app.use(lazyPlugin);
app.use(pinia);
app.use(router);
app.use(componentPlugin);
app.mount('#app');
